import Head from "next/head";
import styles from "src/styles/Project.module.css";
import Footer from "src/components/Footer";
import Container from "src/components/Container";
import Header from "src/components/Header";
import Card from "src/components/Card";
import Hero from "src/components/Hero";
import ProjectHeader from "src/components/ProjectHeader";
import ProjectImage from "src/components/ProjectImage";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container className={styles.container}>
        <ProjectHeader />
        <ProjectImage />
        <Footer />
      </Container>
    </>
  );
}
