import Head from "next/head";
import styles from "src/styles/Home.module.css";
import Footer from "src/components/Footer";
import Container from "src/components/Container";
import Header from "src/components/Header";
import Card from "src/components/Card";
import Hero from "src/components/Hero";
import Window from "src/components/Window";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Hero />
        <div className={styles.cardGrid}>
          {[...Array(10)].map((_, i) => (
            <Card
              key={i}
              href="/"
              title="Suitcase App"
              description="Travel Smart & Safely"
              src="https://framerusercontent.com/images/20Q4dD9CnRYkEPZFRBWrWEWIAc.webp"
            />
          ))}
        </div>
        <Window />
        <Footer />
      </Container>
    </>
  );
}
