import Head from "next/head";
import styles from "src/styles/Projects.module.css";
import Footer from "src/components/Footer";
import Container from "src/components/Container";
import Header from "src/components/Header";
import Card from "src/components/Card";
import Hero from "src/components/Hero";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container className={styles.container}>
        <Hero
          title="Projetos"
          description="Não criamos apenas marcas, criamos experiências inesquecíveis que deixam uma impressão duradoura."
          invert
        />
        <div className={styles.cardGrid}>
          {[...Array(10)].map((_, i) => (
            <Card
              key={i}
              href="/"
              title="Suitcase App"
              description="Travel Smart & Safely"
              src="https://framerusercontent.com/images/20Q4dD9CnRYkEPZFRBWrWEWIAc.webp"
              className={i === 2 ? styles.bigCard : ""}
            />
          ))}
        </div>
        <Footer />
      </Container>
    </>
  );
}
